include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - [build/**]
    - "**/*.g.dart"
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_super_parameters: true
    camel_case_types: true
    empty_statements: false
    prefer_relative_imports: true
    avoid_type_to_string: true
    comment_references: true




