name: ledger_dashboard_chart
description: "A dashboard chart that displays the ledger for an individual user."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.6
  dio: ^5.4.0
  retrofit: ^4.0.3
  flutter_hooks: ^0.20.4
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6


flutter:
  uses-material-design: true